name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.17', '1.18']

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        id: go
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: go.sum

      - name: Install Go modules
        run: go mod download

      - name: Run CI
        run: make ci
